server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb+srv://ashandhanushka:Mashi123@tablex.q2ab2lu.mongodb.net/TableX_db?retryWrites=true&w=majority
  mail:
    host: smtp.gmail.com
    port: 465
    username: ashandhanushka16@gmail.com
    password: xfnd ndtk qnqt imrd
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            protocols: TLSv1.2
            trust: smtp.gmail.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

  # IMPORTANT: This block prevents Spring from creating a default RabbitMQ connection
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

rabbitmq:
  enabled: false